### ISSUE TITLE
Base spawning in Homeworld Sector

### ISSUE THREAD

**Issue by BobTheGimp** [B-iggy/HWS-Plus-Creative-Scenario#1]
Hi, the current playfield YAML for Homeworld Sector does not allow Base Spawning. Are you able to update this in the next release so that we done have to manually change this so we can test base builds etc.
Cheers
Michael

**Comment by B-iggy** [comment]
Hey,
sure! Pushed in https://github.com/B-iggy/HWS-Plus-Creative-Scenario/commit/74ad5df90b6129f40cfbc34832bd8cd43533d7e6
Thanks for the hint.
