### ISSUE TITLE
...In front with empty hands against resist to all enemies

### ISSUE THREAD

**Issue by AgentMasters** [B-iggy/HWS-Plus-Creative-Scenario#10]
In the Main Quest: Protect the Laboratory. how suggest to fight with Elemantals if first time failed to kill them and all invetory was wiped?! You appear in front with empty hands against resist to all enemies?!  (asking as new player on hws+ with nothing in ocd)

**Comment by AgentMasters** [comment]
Also in mission in HQ Collect Ice Blocks - how to fit 30k blocks in invetory if there can put only 20k?
![40e45e89498ca3d79cdf7374c672f5d8](https://user-images.githubusercontent.com/107882107/174664477-020d970b-a36e-4a38-954b-cc509c2e6a65.png)
!

**Comment by B-iggy** [comment]
Sorry for the delay. I'm working on it.
The drop inventory when time runs out or logout is currently configured and happens for everyone.
We try to change the design.

And about Ice Blocks, I'll fix it too today, thanks for the report.

**Comment by AgentMasters** [comment]
Notice that on some POIs on ECC planet is not teleport back. Lile Origin change monolit - there is teleport to it from HQ, but not teleport back to HQ...

**Comment by AgentMasters** [comment]
You fixed the stacks size - thanks! Make the same please for the crop products.
