### ISSUE TITLE
Cannot Enter Terratano Planet

### ISSUE THREAD

**Issue by DeonUn** [B-iggy/HWS-Plus-Creative-Scenario#11]
![image](https://user-images.githubusercontent.com/107777130/174709566-b013ccf5-cda2-41eb-9a42-227c63ffd5f2.png)
Terratano Planet has not let me enter for the past two days.  Upon entering the atmosphere, my ship is bounced back into the Terra Sector.  Have not yet been able to confirm if other players have had the same experience.

**Comment by B-iggy** [comment]
Please try again. Should be fixed now.

**Comment by DeonUn** [comment]
I can confirm that Terratano is now allowing vehicles to enter the atmosphere.  You can close this issue.  Thanks for taking the time to address.

-Deon
