### ISSUE TITLE
Thruster values higher in the creative scenario than the NA server.

### ISSUE THREAD

**Issue by BobTheGimp** [B-iggy/HWS-Plus-Creative-Scenario#12]
The thruster values used by the creative scenario are different from the in-game values resulting in about a 30%ish loss of thrust from when designed in the scenario and then spawned in game.
Is it possible to fully synchronise all the ecf files from the release server version to the creative scenario? While it is readily apparent in the thruster comparison, I have not tried to do a full comparison of other placeables along with sychronising the constructor recipes etc.

**Comment by B-iggy** [comment]
Hmm Thruster values should be the same.
Are you sure you are using in your Scenario M/V set to ON?
![image](https://user-images.githubusercontent.com/7815434/175471300-b575c07c-a418-4d63-8693-0d65d8788e98.png)
![image](https://user-images.githubusercontent.com/7815434/175471329-92d9a7f7-262b-437c-b7b8-5b751ea98d33.png)

I'll do another round of tweaks today and push everything again, just in case

**Comment by BobTheGimp** [comment]
I have checked, the thrust figures are the same, it must be something else. you can close this issue.
