### ISSUE TITLE
To the Stars mission 

### ISSUE THREAD

**Issue by AgentMasters** [B-iggy/HWS-Plus-Creative-Scenario#13]
In that mission you recieve 300 wood blocks but you cant place them... ( Maybe need to build some ladder, but you cant build on that location! Also teleport back to ECC HQ not work!

**Comment by B-iggy** [comment]
Thanks, I'll put it on my note and try to fix today!

**Comment by B-iggy** [comment]
Nevermind. I played the mission myself and it works.
![image](https://user-images.githubusercontent.com/7815434/181035444-e28934ba-d685-49cc-9fc4-9bbec92730ca.png)

It's just a very difficult one and requires currently a Multi tool to complete. I'll add 400 Wood Blocks to make it easier doable.
