### ISSUE TITLE
Teleports bug

### ISSUE THREAD

**Issue by AgentMasters** [B-iggy/HWS-Plus-Creative-Scenario#14]
Very often teleports cause endless loading of the sector and I have to restart the game. If this happens during a mission, it fails

**Comment by B-iggy** [comment]
Can you let me know which one exactly please? From where to where?

**Comment by AgentMasters** [comment]
That was 4 ago. My friend tell me that he notice that bug too. On next day i manage to teleport without endless loads on teleport.  
On hws+ mission teleports are very important! They are main way to mine ore, because there is no other orbits with asteroids. Also in combat missions the personal armor lose durability very fast - even on low level missions! Please lower incoming damage from npcs! The armor boosters are not work - as result the player cant jump enought high to complete some jump and run missions...

**Comment by B-iggy** [comment]
Armor durability is on my list already.
Regarding teleports, without knowing the exact destinations, I can't check.
Teleporters are in general buggy in Empyrion in MP.
