### ISSUE TITLE
Origin/Elemental Ammo for Protect the Laboratory mission

### ISSUE THREAD

**Issue by Jumarak** [B-iggy/HWS-Plus-Creative-Scenario#15]
The first time I tried to do the Protect the Laboratory mission several days ago I wasn't given any guns or ammo, so I couldn't do it.

I tried again today and thankfully got the elemental guns and 5 ammo for each (including my origin gun), but it doesn't seem anywhere near enough. I now have an empty terra gun, empty pyro gun, and 2/5 origin gun, and I've only managed to kill one monster.
The mission says I have to kill 3, although I think it originally said 8 before I killed the first one.

How am I meant to complete this mission if I've almost run out of ammo trying to kill one monster? I can't find any other ways of getting ammo for these guns. There needs to be a way to replenish this ammo, especially if players run out simply due to poor aim.

Edit: After respawning on my starter planet after death I am not missing two of the elemental guns, so we probably need a way to regain these as well as extra ammo.

**Comment by AgentMasters** [comment]
https://github.com/B-iggy/HWS-Plus-Creative-Scenario/issues/10 i have the same issue - i complete the mission using my survival tool ) It was hard but until this was not fixed all players will be suffer there
![unknown](https://user-images.githubusercontent.com/107882107/179447683-8e710dad-fa60-40fa-b603-78287118dd2c.png)

**Comment by B-iggy** [comment]
A rework of this mission is coming this week.
It all takes a lot of time to built...

(And patch 1.8.5 will fix the blast damage of NPC materials. It never worked actually, in RE as well)

**Comment by AgentMasters** [comment]
There is only 5 ammo - that is not enought to kill the beasts. Also you have fire, water and earth guns - how to kill earth elemental?

**Comment by B-iggy** [comment]
you also have a Pyro gun

**Comment by AgentMasters** [comment]
i use it against water elemental

**Comment by B-iggy** [comment]
![HWS-Elemental-Effectiveness](https://user-images.githubusercontent.com/7815434/181189807-3f191d3e-a98a-4d2f-8154-ff45331ae9e2.png)
