### ISSUE TITLE
Respawn on starter planet resets inventory

### ISSUE THREAD

**Issue by Jumarak** [B-iggy/HWS-Plus-Creative-Scenario#17]
dying and selecting the respawn on starter planet resets your inventory, which includes removing any armor/boosters or mission tokens etc.

I'm not sure if this is intentional behaviour, but if it is then it should be made clearer to the player before they select that option.

**Comment by B-iggy** [comment]
on which starter planet please?
I think this is technically how it works in Empyrion but I can try to improve it.

**Comment by Jumarak** [comment]
This was respawning on Exa, the explorer starter planet.
