### ISSUE TITLE
Black Hole Miner do not work correctly

### ISSUE THREAD

**Issue by AgentMasters** [B-iggy/HWS-Plus-Creative-Scenario#21]
![image](https://user-images.githubusercontent.com/107882107/179668704-60b13c5e-2b84-4349-a86f-cb3d71f8d68d.png)

In Black Hole Miner only red swich open red containers - no matter do you swich right combination or not!

**Comment by AgentMasters** [comment]
And there is no "J" to complete Brown combination!

**Comment by B-iggy** [comment]
We did not change this puzzle, so it works and you need to figure out the puzzle.

**Comment by AgentMasters** [comment]
How to know wich swiches need to be ON and OFF - i turn ON all swiches that need by the screen - How to turn ON the swich that need for Brown color containers if there  need "J" but no letter J in that room ?! How it works?

**Comment by B-iggy** [comment]
It's a puzzle mate. Try to figure it out yourself or ask others.
