### ISSUE TITLE
Wrong origin gun!

### ISSUE THREAD

**Issue by AgentMasters** [B-iggy/HWS-Plus-Creative-Scenario#22]
Im notice that my DNA go not converted  in XP?! egs:info not show the origin info of the player. I know that im explorer just because i have structure on Exa - this is the starter planet of explorers. But why my origin gun are Engineer?!

**Comment by B-iggy** [comment]
> Im notice that my DNA go not converted in XP?!
>  But why my origin gun are Engineer?!

I don't know what you mean.
If you started on Exa you got an Explorer Gun. At least I checked and it's not a bug.

**Comment by AgentMasters** [comment]
Yes im start on Exa but i  have engineer gun - Please can you give me the Explorer gun?

**Comment by AgentMasters** [comment]
![image](https://user-images.githubusercontent.com/107882107/181198293-c4bc066d-90b4-4bd5-a7e2-652fb438135e.png)
What will do with this gun now - its not for me

**Comment by B-iggy** [comment]
Normally a support ticket is needed for that.
Github is NOT for support tickets!!
Only for feedback / issues about configs etc.
