### ISSUE TITLE
Rocket launcher and armor boosts!!!

### ISSUE THREAD

**Issue by AgentMasters** [B-iggy/HWS-Plus-Creative-Scenario#23]
![image](https://user-images.githubusercontent.com/107882107/180933303-8c5bd5f2-0349-4c28-a3bc-ab859a1a7c67.png)

THe gamage of rocket launcher are 1?!? Rex why you didnt fix the bugs that we post here?! You create bautifull world with many interesting quest and new POIs - why i need to die 1000 times and ruin my RP with heavy armor that not protect me?! Please leave the chess play and get to work!

**Comment by B-iggy** [comment]
I will get to it asap.
I will fix all bugs you post here or in Discord.
It's just a lot and I'm currently spending a lot of time reworking the TSCG / Starfragment logic.
Please have a bit more patience.

**Comment by B-iggy** [comment]
Fixed in HWS+ Beta
