### ISSUE TITLE
Salvage from Turrets

### ISSUE THREAD

**Issue by AgentMasters** [B-iggy/HWS-Plus-Creative-Scenario#24]
THe salvage from all type turrets is very low - This is the salvage from Alien Laser Turrets (BA) 
![image](https://user-images.githubusercontent.com/107882107/181426389-9eb508ca-2efc-4064-9a88-a7b748b72065.png)

Its lower than salvaging a decor

**Comment by B-iggy** [comment]
This is not new and since years the case. The return % rate is lower on HWS.

**Comment by AgentMasters** [comment]
> This is not new and since years the case. The return % rate is lower on HWS.

You mean that % rate is lower than on HWS ? Beacuse on HWS you can salvage all type turrets and salvage is good (excluded some turrets from legacy ships!) 
Also i have to ask On HWS+ Recycle lvl5 can we salvage the turrets and what type of them? I still support my opinion that Recycle deserv his own menu tab on connect site! For new players is hard to find it in structure command and there is only links to manuay import the commands - no info for current lvl Recycle and these command i think have not right description! In Connect menu there is a lot of tabs that ppl never use but not tabs that we need! ( Sorry Bob - you cant answer me here as you often do instead of Rex in discord)

**Comment by B-iggy** [comment]
> You mean that % rate is lower than on HWS ? Beacuse on HWS
What do you mean? HWS HWS?
You mean HWS RE vs. HWS+?
Yes, on HWS+ it was always lower, for certain reasons.

With EGS Recycle you can recycle turrets and get the parent block back.

> I still support my opinion that Recycle deserv his own menu tab on connect site!
That's legit and I try to implement it once possible.

**Comment by AgentMasters** [comment]
![image](https://user-images.githubusercontent.com/107882107/181487032-4e16e456-c35e-4f9a-9bc4-0d1703b755ac.png)
![image](https://user-images.githubusercontent.com/107882107/181487181-0732a88e-52b3-4090-aa52-13614aa29788.png)

> > You mean that % rate is lower than on HWS ? Beacuse on HWS
> > What do you mean? HWS HWS?
> > You mean HWS RE vs. HWS+?
> > Yes, on HWS+ it was always lower, for certain reasons.

This is the salvage the same turret on HWS RE EU

**Comment by B-iggy** [comment]
Yep. As I said, HWS (old) and HWS+ have a smaller return % factor on Deconstructors and Multitools.
I will reconsider this decision, since we don't have 4000000 stars.
