### ISSUE TITLE
The old Repair Console bug!

### ISSUE THREAD

**Issue by AgentMasters** [B-iggy/HWS-Plus-Creative-Scenario#25]
Please, can you fix the old problem with repair console! I cant stay all day near console so it can restore my ship! I know that is the old problem and Eleon refuse to fix it - if you left the sector (or disconnect) and come back, the repair time is reset (  This can be fix very easy - repair can be set by same way like Extractors - they mine without player need to sit near! As it is now implemented it is useless!

**Comment by B-iggy** [comment]
> if you left the sector (or disconnect) and come back, the repair time is reset

Really?? Is this 100% reproducible??

**Comment by AgentMasters** [comment]
Yes

**Comment by AgentMasters** [comment]
Its my post since 2019  https://empyriononline.com/threads/ship-repair-with-repair-bay-t2-at-my-base-canceled.97505/

**Comment by B-iggy** [comment]
In HWS+ Beta in every orbit there is a HWS Racom station. That means you can repair and buy ammo there.
I'll also increase the repairbay speed a lot.
