### ISSUE TITLE
Mad guard!

### ISSUE THREAD

**Issue by AgentMasters** [B-iggy/HWS-Plus-Creative-Scenario#27]
There is a mad guards on Kennex station that shoot on me! They are no tag Polaris in name but the same color - my standing is Friendly!
![image](https://user-images.githubusercontent.com/107882107/182013061-63797930-76d2-42d2-9764-b7be8a8c015d.png)

![image](https://user-images.githubusercontent.com/107882107/182012838-47db171b-90ee-442e-afb3-941df7a39893.png)
![image](https://user-images.githubusercontent.com/107882107/182012878-ebf4db74-68ac-4d14-9e29-72ca0e62166b.png)

**Comment by B-iggy** [comment]
I have no control over it. Kennex is vanilla stuff, placeholder for the HWS+ Alpha version, replaced in the next season.
