### ISSUE TITLE
Biome warp loading

### ISSUE THREAD

**Issue by Jumarak** [B-iggy/HWS-Plus-Creative-Scenario#3]
Character: Jumarak
Time: ~18:15 UTC
I reached the end of the clone academy as an explorer and attempted to use the biome warp to go to the Savannah biome. The loading screen came up and seemed to just be constantly loading. I left it for at least a couple of minutes before I quit the game. When I reconnected I was in some kind of basement area of the EGS Iron Ore factory on the Exa planet.

The only thing I can think of that might have contributed to this was that I think I levelled up a skill via HWS connect while I was in the warp loading screen.

**Comment by B-iggy** [comment]
Thank you very much for doing this issue here in github!  :)
We found the issue and will fix it for the next server restart.
