### ISSUE TITLE
POI

### ISSUE THREAD

**Issue by darkvei** [B-iggy/HWS-Plus-Creative-Scenario#4]
when starting on a pvp planet with a survivor's tool in protection mode, when removing a flowerbed or any block of the POI base, the entire structure of the base is completely destroyed, is this how it should be? I'm writing through a translator so I'm sorry if it's not very clear

**Comment by B-iggy** [comment]
Oh, no, that sounds bad.
Can you tell me please on which planet you started?

**Comment by darkvei** [comment]
I started at the start, and my friend at Homeworld and it was there. he asked me to write to you . sorry, but when choosing the system it was Homeworld and what planet is there, I do not know, he has already gone to bed, I cannot specify, and I wanted to ask about the spawn of a free ship, it is not possible to fly on it, the speed is 30, as if it is very overloaded, maybe of course it should be

**Comment by darkvei** [comment]
and I also wanted to ask, when training and passing, they give a token to enter a closed room, there is an OCD teleporter there. but it doesn't work, there is an eternal download and you have to quit the game , maybe if it doesn't work, you need to temporarily disable it?

**Comment by B-iggy** [comment]
Ok, I think most of your points should be fixed by now.
If now, can you please comment with details here?

**Comment by darkvei** [comment]
at the clone academy station in a closed room , the OCD teleport does not work , there is an eternal download , I have to leave the game , I did it now

**Comment by darkvei** [comment]
and after entering the game again , I appear in this room , and a robot kills me , and now I can 't go into this room to pick up my backpack , because I need a token that remains in it , there used to be a code on this door and it was possible to re - enter , as it is not clear now

**Comment by B-iggy** [comment]
ah ok. We will fix this in few minutes. thanks for the report
