### ISSUE TITLE
Error on retrieving base core

### ISSUE THREAD

**Issue by Jumarak** [B-iggy/HWS-Plus-Creative-Scenario#5]
Character: Jumarak
Time: 18/06/2022 00:20 UTC

I used a multi tool to retrieve a core deployed from a base starter kit on the explorer starter world. This caused an error.

**Comment by B-iggy** [comment]
Hmm, I tried to place a base starter block on the terrain and used multi tool on it. No error.
Can you drag and drop your log file here, so I can check?

**Comment by Jumarak** [comment]
I think this is the relevant log file

**Comment by B-iggy** [comment]
Thanks, I'll send it to the devs if I know more.
