### ISSUE TITLE
POI

### ISSUE THREAD

**Issue by darkvei** [B-iggy/HWS-Plus-Creative-Scenario#6]
the Homeworld PvP system is the starting planet, POI are destroyed with one shot almost completely S-0 .S-2 and so on

**Comment by B-iggy** [comment]
Which POI do you mean please?

**Comment by darkvei** [comment]
they are basically all there with the names S-2 F1, all of which I have met on the planet are all collapsing, some with 1 shot, some with 2 shots, and I wanted to ask on the energetic tower there is a sign of a spawn ship, but when you enter a command, he writes that you need to be in the zone, it is not clear, and yes, he created a drawing of the ms but it turned out without a cabin

**Comment by darkvei** [comment]
Temple . Agueduct .Forest Care Center

**Comment by B-iggy** [comment]
Ah ok, thanks. We will check that.
