### ISSUE TITLE
Pyro Element Discrepancies

### ISSUE THREAD

**Issue by DeonUn** [B-iggy/HWS-Plus-Creative-Scenario#7]
Pyronia Planet has Pyro Element points of interest: [Aqua] Pyro Element within Aqua territory.
![image](https://user-images.githubusercontent.com/107777130/174460628-f782ff0f-a2c0-471a-935c-b302ea426597.png)

Pyrosec Planet has Pyro Element points of interest: [Aqua] Small Pyro Element within Aqua territory.
![image](https://user-images.githubusercontent.com/107777130/174460659-1bf93ee8-5ee3-4078-bcfd-3a24ea7adc85.png)

Pyromal Planet has Pyro Element points of interest: [Pyro] Big Pyro Element within Pyro territory.
![image](https://user-images.githubusercontent.com/107777130/174460672-1cee5f9e-f430-4d80-a4e8-0feded557188.png)

Pyronia elemental poi's belong to incorrect "Faction" Aqua, should be Pyro faction inside of Pyro territory?
Pyrosec elemental poi's belong to incorrect "Faction" Aqua, should be Pyro faction inside of Pyro territory?
Pyromal elemental poi's belong to the correct "Faction" within the correct territory.

I apologize in advance if I don't know what I'm speaking about, it just seems that the "Aqua" relationship is out of place on "Pyro" points of interest.

Deon

**Comment by B-iggy** [comment]
Thanks for the report Deon. I corrected the Aqua faction for Pyro POIs hopefully.
