### ISSUE TITLE
Origin weapon

### ISSUE THREAD

**Issue by darkvei** [B-iggy/HWS-Plus-Creative-Scenario#8]
![20220620183819_1](https://user-images.githubusercontent.com/107724149/174638520-57d74669-b798-454d-8419-41e957c2d712.jpg)
![20220620183823_1](https://user-images.githubusercontent.com/107724149/174638577-2a2ca269-e999-4d87-80f1-0c114aab384d.jpg)
I have an origin weapon and HWS XP , but it does not go into rp , the Homeworld starting planet . I was able to get the ship , but for some reason it will spawn on one energy tower , and it 's easy to climb up to the tower , but the problem has to jump down because the elevator block works very quickly , and I wanted to find out my bank was level 5 and today it shows that it is the first level , so it should be ? or do I need to create a ticket? cargo drone 5 damage and remained ,and if the ship is loaded with 6 stacks , it does not fly at all , although the weight shows zero , how and from what then it is not clear

**Comment by B-iggy** [comment]
Hello darkvei,
thanks for your report.
The reason was an issue, that players started on Homeworld got an Engineer Origin Weapon instead of a Fighter Origin Weapon.
I replaced your Origin gun now.

**Comment by B-iggy** [comment]
Regarding your other issue: 
• I'll check the Lifts to go down the tower. Your Jetpack helps.
• will check the starter SV you spawn with egs:spawn. 
• The Elemental Bank level resets every season to level 1. that is right.
see here: https://forum.empyrion-homeworld.net/t/elemental-bank-eb/4395
