### ISSUE TITLE
Destruction of buildings

### ISSUE THREAD

**Issue by TTK123TTK** [B-iggy/HWS-Plus-Creative-Scenario#9]
Destruction of buildings with a single pulse of weapons in defensive mode, all buildings fall apart almost completely for scrap on the PVP planet homeworld

**Comment by TTK123TTK** [comment]
homeworld

**Comment by B-iggy** [comment]
Ok thanks. We will check this.

**Comment by B-iggy** [comment]
We found the issue and fixed this for the next server restart. Si: off was missing. Thanks!
